In [2]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.stats import norm
from tqdm import tqdm

# append path
sys.path.append('../')
from process.tables import *
from setpts.bayes import *
# from setpts.predict import *
from process.config import *
from setpts.utils import *
from process.config import *
from setpts.gmm import *
from setpts.bayes import *
from setpts.ornstein_uhlenbeck import *

In [3]:
ou1

,subject_id,test_name,sex,age,setpoint_mean,setpoint_var,setpoint_date,prior_mean,priot_var
0,115967116,HCT,F,23.126626,35.531429,0.198522,2014-07-26 12:42:00,None,None
1,115967116,PT,F,23.126626,13.890025,0.007310,2014-07-26 12:42:00,None,None
2,115967116,WBC,F,23.126626,4.866910,0.013559,2014-07-26 12:42:00,None,None
3,115967124,ALB,F,60.306639,4.884990,0.001035,2012-09-22 12:45:00,None,None
4,115967124,ALP,F,60.306639,-1.340387,6.830008,2012-09-22 12:45:00,None,None
...,...,...,...,...,...,...,...,...,...
19844,115973825,RDW,M,30.743326,4.666780,0.001143,2016-12-18 13:44:00,None,None
19845,115973825,TBIL,M,30.743326,0.501482,0.000280,2016-12-18 13:44:00,None,None
19846,115973825,TP,M,30.743326,9.121904,0.000743,2016-12-18 13:44:00,None,None
19847,115973825,WBC,M,30.743326,4.309030,0.005297,2016-12-18 13:44:00,None,None
19848,115973826,A1C,M,62.206708,0.420152,0.001643,2016-06-25 15:04:00,None,None

In [4]:
ou2

,subject_id,test_name,sex,ou_prior_mean,ou_prior_var,ou_prior_sigma_mean,ou_prior_sigma_var,ou_mean,ou_speed,ou_std,ou_var,n_measurements,dt_mean
0,115967116,HCT,F,42.00,6.250000,2.500,0.2,37.937555,1.000000,1.092014,1.192495,3,203.001389
1,115967116,PT,F,11.50,0.562500,0.750,0.2,11.500000,NaN,0.750000,0.562500,0,0.000000
2,115967116,WBC,F,7.75,2.640625,1.625,0.2,5.591965,1.000000,0.723414,0.523329,10,93.089931
3,115967124,ALB,F,4.50,0.250000,0.500,0.2,4.000571,0.334395,0.500000,0.250000,2,138.016319
4,115967124,ALP,F,70.00,400.000000,20.000,0.2,97.288356,1.000000,9.703317,94.154368,3,92.010880
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19844,115973825,RDW,M,11.75,1.890625,1.375,0.2,13.659517,1.000000,0.598623,0.358350,5,240.031528
19845,115973825,TBIL,M,0.15,0.005625,0.075,0.2,0.150000,NaN,0.075000,0.005625,0,0.000000
19846,115973825,TP,M,7.00,0.250000,0.500,0.2,7.765863,1.000000,0.182839,0.033430,4,300.039410
19847,115973825,WBC,M,7.75,2.640625,1.625,0.2,6.791183,1.000000,0.673553,0.453674,5,240.031528
19848,115973826,A1C,M,4.80,0.160000,0.400,0.2,4.800000,NaN,0.400000,0.160000,0,0.000000